### ISSUE TITLE
About the preprocess?

### ISSUE THREAD

**Issue by fangtao365** [EdgarMoyete/Deep-Learning-BCI-IV-2a#2]
Hello, I would like to ask what are the preprocessing steps of the data? The data format is ndarray: (288 ~ 22 ~ 1000). Does it include artifact removal, such as ICA? Is a rereference used? Is baseline correction done?

**Comment by EdgarMoyete** [comment]
Hello, the data does not have any preprocessing
there are 288 samples of 22 channels with 4 seconds with a sample rate of 250Hz
ICA was not used
no reference was used
and no baseline correction was used
here you can find a more detailed work
https://github.com/EdgarMoyete/EEG-Classification-with-CNN
Any questions contact me at edgar.h@inaoep.mx
