### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ismailishaq132** [EdgarMoyete/Deep-Learning-BCI-IV-2a#3]
Can you provide the csv of the dataset?

**Comment by ManTouCIBR** [comment]
Please provide the four files of CSV. Thank you very much！！！

**Comment by EdgarMoyete** [comment]
more information in https://github.com/EdgarMoyete/EEG-Classification-with-CNN
you can create the csv with the original datasets
they weigh several mb to pass them

**Comment by EdgarMoyete** [comment]
The datasets with preprocessing in .csv are already available in: https://github.com/EdgarMoyete/EEG-Classification-with-CNN
