### ISSUE TITLE
Email about consulting csv

### ISSUE THREAD

**Issue by ManTouCIBR** [EdgarMoyete/Deep-Learning-BCI-IV-2a#4]
Hello sir, I sent an email to your email on 2022.08.10, my email is 1906703957@qq.com If you see it, please check it out during your busy schedule, thank you very much!

**Comment by EdgarMoyete** [comment]
Hello, I have not received any email, but if you like, tell me by this means what you need

**Comment by ManTouCIBR** [comment]
> Hello, I have not received any email, but if you like, tell me by this means what you need

Hello author, I am a beginner of deep learning, and I don't know much about what you said about extracting CSV from original data, so I would like to ask you for four CSV files of A01T used for cross-validation. The format of their data is (288,510). If you are willing to do so, please send the files to the following email address:1906703957@qq.com or   x1906703957@163.com.Thank you very much!

**Comment by ManTouCIBR** [comment]
> Hello, I have not received any email, but if you like, tell me by this means what you need

: hello, the author, the four CSV file upload AlfaC3C4 file is you do cross validation in CNN - 1 d - A01T. MI EEG - Alfa CSV, MI - EEG - Alfa - A01E. CSV, AlfaC3C4 / EtiquetasA01T CSV, AlfaC3C4 / EtiquetasA01E. Four CSV files.

**Comment by EdgarMoyete** [comment]
I will upload the .CSV that I have and I will put the download link in the following repository: 
https://github.com/EdgarMoyete/EEG-Classification-with-CNN

**Comment by ManTouCIBR** [comment]
> I will upload the .CSV that I have and I will put the download link in the following repository: https://github.com/EdgarMoyete/EEG-Classification-with-CNN

Hello, thank you very much for your help. I have found the CSV file I want, which will help me a lot on the way to deep learning!
